// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhPsDYs2ny9KVxJ1WtTAwnatQ_Ck5U6z4',
    appId: '1:184465845242:web:d770a51f629214577dd243',
    messagingSenderId: '184465845242',
    projectId: 'azkark-f3ff3',
    authDomain: 'azkark-f3ff3.firebaseapp.com',
    storageBucket: 'azkark-f3ff3.firebasestorage.app',
    measurementId: 'G-FLJ4DYS0S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx48R1W8QmIiXZ81i_oAKSwM0vIz3oVT4',
    appId: '1:184465845242:android:4dafce1ea4faef4d7dd243',
    messagingSenderId: '184465845242',
    projectId: 'azkark-f3ff3',
    storageBucket: 'azkark-f3ff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhzaIpqg_y2U1sTw9HD_tLwr2A_-ti6Vk',
    appId: '1:184465845242:ios:cd4bdd763f3f4ffd7dd243',
    messagingSenderId: '184465845242',
    projectId: 'azkark-f3ff3',
    storageBucket: 'azkark-f3ff3.firebasestorage.app',
    iosBundleId: 'com.example.azkark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhzaIpqg_y2U1sTw9HD_tLwr2A_-ti6Vk',
    appId: '1:184465845242:ios:cd4bdd763f3f4ffd7dd243',
    messagingSenderId: '184465845242',
    projectId: 'azkark-f3ff3',
    storageBucket: 'azkark-f3ff3.firebasestorage.app',
    iosBundleId: 'com.example.azkark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhPsDYs2ny9KVxJ1WtTAwnatQ_Ck5U6z4',
    appId: '1:184465845242:web:fbe7bbf8f0af3cd37dd243',
    messagingSenderId: '184465845242',
    projectId: 'azkark-f3ff3',
    authDomain: 'azkark-f3ff3.firebaseapp.com',
    storageBucket: 'azkark-f3ff3.firebasestorage.app',
    measurementId: 'G-L07DMH2ZSY',
  );
}
